FROM node:12.8.0

RUN npm install -g n
RUN n 12.18.0
RUN npm install --global @vue/cli

# WORKDIR /projects

# ADD ./package.json /quiz-project/package.json
# ADD ./start.sh /quiz-project/start.sh

WORKDIR /projects/quiz-project
